## First Simple Neural Network

In [2]:
weight = 0.1
def neural_network(inputs,weight):
    prediction = inputs * weight
    return prediction

number_of_toes = [8.5,9.5,10,9]
inputs = number_of_toes[0]
pred = neural_network(inputs, weight)
print(pred)

0.8500000000000001



## Accepting multiple weights

In [10]:

## WEIGHTS
weights = [0.1, 0.2, 0]
## INPUTS
toes = [8.5, 9.5, 9.9, 9.0]
wlrec = [0.65, 0.8, 0.8, 0.9]
nfans = [1.2, 1.3, 0.5, 1.0]


inputs = [toes[0], wlrec[0], nfans[0]]

def w_sum(a,b):
   
    
    assert(len(a) == len(b))
    output = 0
    for i in range(len(a)):
        output += (a[i] * b[i])
    return output
    

def neural_network(inputs, weights):
    pred = w_sum(inputs,weights)
    return pred

neural_network(inputs,weights)


0.9800000000000001

In [25]:
def elementwise_addition(vect_a, vect_b):
    assert(len(vect_a) == len(vect_b))
    output = [0] * len(vect_a)
    print(output)
    for i in range(len(vect_a)):
        output[i] = vect_a[i] + vect_b[i]
    return output

def elementwise_multiplication(vect_a, vect_b):
    assert(len(vect_a) == len(vect_b))
    output = [0] * len(vect_a)
    print(output)
    for i in range(len(vect_a)):
        output[i] = vect_a[i] * vect_b[i]
    return output

def vector_sum(vect_a):
    output = 0
    for i in range(len(vect_a)):
        output += vect_a[i]
    return output

def vector_average(vect_a):
    sum = vector_sum(vect_a) / len(vect_a)
    return sum


toes = [8.5, 9.5, 9.9, 9.0]
wlrec = [0.65, 0.8, 0.8, 0.9]


print(vector_average(toes))

9.225


## Using Numpy
Numpy makes it a lot easier to do dot products on an array

In [34]:
import numpy as np

## WEIGHTS
weights = np.array([0.1, 0.2, 0])
## INPUTS
toes = np.array([8.5, 9.5, 9.9, 9.0])
wlrec = np.array([0.65, 0.8, 0.8, 0.9])
nfans = np.array([1.2, 1.3, 0.5, 1.0])

def neural_network(inputs, weights):
    pred = weights.dot(inputs)
    return pred

inputs = np.array([toes[0], wlrec[0] , nfans[0]])



print(neural_network(inputs,weights))


    


[5.525, 7.6000000000000005, 7.920000000000001, 8.1]
0.9800000000000001


## Using Numpy to do vector things

In [42]:
## Addition
added = toes + wlrec

## Multiply
multiply = toes + wlrec

## Vector sum
sums = toes.sum()

## average
averages = np.average(toes)

print(f"Added as {added}\nMultiplied as {multiply}\nVector Sum is {sums}\nAverage Vector is {averages}")



Added as [ 9.15 10.3  10.7   9.9 ]
Multiplied as [ 9.15 10.3  10.7   9.9 ]
Vector Sum is 36.9
Average Vector is 9.225


## Distributing single data to predict multiple outputs

In [50]:
weight = [0.3, 0.2, 0.9]
def predict_sad_hurt_and_all(inputs, weights):
    output = [0] * len(weights)
    for i in range(len(output)):
        output[i] = inputs * weights[i]
    return output

def using_numpy(inputs,weights):
    np_weights = np.array(weights)
    return np_weights * inputs
    
wlrec = [0.65, 0.8, 0.8, 0.9]
inputs = wlrec[0]
print(using_numpy(inputs, weight))
print(predict_sad_hurt_and_all(inputs, weights))

[0.195 0.13  0.585]
[0.065, 0.13, 0.0]


In [63]:
#           toes win fans
weights = [[0.1, 0.1,-0.3], # hurt 
           [0.1, 0.2, 0.0], # win 
           [0.0, 1.3, 0.1]] # sad

toes = [8.5, 9.5, 9.9, 9.0]
wlrec = [0.65,0.8, 0.8, 0.9]
nfans = [1.2, 1.3, 0.5, 1.0]


inputs = [toes[0],wlrec[0],nfans[0]]

def w_sum(a,b):
    assert(len(a) == len(b))
    output = 0
    for i in range(len(a)):
        output += (a[i] * b[i])
    return output

def vect_mat_mul(vector , matrix):
    assert(len(vector) == len(matrix))
    output = [0,0,0]
    for i in range(len(vector)):
        
        output[i] = w_sum(vector, matrix[i])
    return output


def neural_network(inputs, weights):
    pred = vect_mat_mul(inputs,weights)
    return pred


print(neural_network(inputs,weights))

[0.555, 0.9800000000000001, 0.9650000000000001]


## Testing Linear Regression

In [1]:
import numpy as np
from sklearn.linear_model import LinearRegression

In [5]:
x = np.array([5, 15, 25, 35, 45, 55]).reshape((-1, 1))
y = np.array([5, 20, 14, 32, 22, 38])

In [7]:
model = LinearRegression().fit(x, y)

In [23]:
model.predict(x)

array([ 8.33333333, 13.73333333, 19.13333333, 24.53333333, 29.93333333,
       35.33333333])

In [25]:
np.array([1,2])

array([1, 2])